-- Generated by TypescriptToLua v0.1.3
-- https://github.com/Perryvw/TypescriptToLua
iron_heat_strike = {}
iron_heat_strike.__index = iron_heat_strike
function iron_heat_strike.new(construct, ...)
    local instance = setmetatable({}, iron_heat_strike)
    if construct and iron_heat_strike.constructor then iron_heat_strike.constructor(instance, ...) end
    return instance
end
function iron_heat_strike.constructor(self)
end
function iron_heat_strike.OnUpgrade(self)
    if IsServer() then 
        self:GetCaster():GetAbilityByIndex(4):SetLevel(1)
    end
end
function iron_heat_strike.GetAOERadius(self)
    if self:GetCaster():HasScepter() then
        return self:GetSpecialValueFor("aoe_scepter")
    end
    return
end
function iron_heat_strike.GetBehavior(self)
    if self:GetCaster():HasScepter() then
        return DOTA_ABILITY_BEHAVIOR_UNIT_TARGET+DOTA_ABILITY_BEHAVIOR_AOE
    end
    return DOTA_ABILITY_BEHAVIOR_UNIT_TARGET
end
function iron_heat_strike.CastFilterResultTarget(self,hTarget)
    if IsServer() then
        if ((hTarget~=nil) and hTarget:IsMagicImmune()) and (not self:GetCaster():HasScepter()) then
            return UF_FAIL_MAGIC_IMMUNE_ENEMY
        end
        local nResult = UnitFilter(hTarget,self:GetAbilityTargetTeam(),self:GetAbilityTargetType(),self:GetAbilityTargetFlags(),self:GetCaster():GetTeamNumber())

        return nResult
    end
    return UF_SUCCESS
end
function iron_heat_strike.OnSpellStart(self)
    if IsServer() then
        local hTarget = self:GetCursorTarget()

        if hTarget then
            if not hTarget:TriggerSpellAbsorb(self) then
                local damage = (self:GetSpecialValueFor("damage_mana_pct")/100) * self:GetCaster():GetMaxMana()

                local sound = "Hero_Lina.LagunaBlade.Immortal"

                if Util:PlayerEquipedItem(self:GetCaster():GetPlayerOwnerID(), "iron_devil") then
                    sound = "IronDevil.CastUlti"
                end

                EmitSoundOn(sound,self:GetCaster())
                
                if self:GetCaster():HasScepter() then
                    damage=(self:GetSpecialValueFor("damage_scepter")/100) * self:GetCaster():GetMaxMana()
                    local units = FindUnitsInRadius(self:GetCaster():GetTeamNumber(), hTarget:GetOrigin(), self:GetCaster(), self:GetSpecialValueFor("aoe_scepter"), DOTA_UNIT_TARGET_TEAM_ENEMY, DOTA_UNIT_TARGET_HERO + DOTA_UNIT_TARGET_BASIC, DOTA_UNIT_TARGET_FLAG_NOT_ILLUSIONS, 0, false)
                    if #units > 0 then
                        for _,unit in pairs(units) do               
                            ApplyDamage({victim=unit,attacker=self:GetCaster(),ability=self,damage=damage,damage_type=DAMAGE_TYPE_MAGICAL})
                            EmitSoundOn("Hero_Lina.LagunaBladeImpact.Immortal",unit)
                            local nFXIndex = ParticleManager:CreateParticle("particles/econ/items/lina/lina_ti6/lina_ti6_laguna_blade.vpcf",PATTACH_CUSTOMORIGIN,nil)

                            ParticleManager:SetParticleControlEnt(nFXIndex,0,self:GetCaster(),PATTACH_POINT_FOLLOW,"attach_ulti",self:GetCaster():GetOrigin()+Vector(0,0,96),true)
                            ParticleManager:SetParticleControlEnt(nFXIndex,1,unit,PATTACH_POINT_FOLLOW,"attach_hitloc",unit:GetOrigin(),true)
                            ParticleManager:ReleaseParticleIndex(nFXIndex)
                            unit:AddNewModifier(self:GetCaster(),self,"modifier_stunned",{duration=1.5})
                        end
                    end
                else
                    ApplyDamage({victim=hTarget,attacker=self:GetCaster(),ability=self,damage=damage,damage_type=DAMAGE_TYPE_MAGICAL})
                    local nFXIndex = ParticleManager:CreateParticle("particles/econ/items/lina/lina_ti6/lina_ti6_laguna_blade.vpcf",PATTACH_CUSTOMORIGIN,nil)

                    ParticleManager:SetParticleControlEnt(nFXIndex,0,self:GetCaster(),PATTACH_POINT_FOLLOW,"attach_ulti",self:GetCaster():GetOrigin()+Vector(0,0,96),true)
                    ParticleManager:SetParticleControlEnt(nFXIndex,1,hTarget,PATTACH_POINT_FOLLOW,"attach_hitloc",hTarget:GetOrigin(),true)
                    ParticleManager:ReleaseParticleIndex(nFXIndex)
                    hTarget:AddNewModifier(self:GetCaster(),self,"modifier_stunned",{duration=1.5})
                    EmitSoundOn("Hero_Lina.LagunaBladeImpact.Immortal",unit)
                end
            end
        end
    end
end
