"qualities"
{
  "1"
  {
    "name" "common"
  }
  "2"
  {
    "name" "uncommon"
  }
  "3"
  {
    "name" "rare"
  }
  "4"
  {
    "name" "mythical"
  }
  "5"
  {
    "name" "legendary"
  }
  "6"
  {
    "name" "ancient"
  }
  "7"
  {
    "name" "immortal"
  }
  "8"
  {
    "name" "ethernal"
  }
  "9"
  {
    "name" "arcana"
  }
  "10"
  {
    "name" "extraordinary"
  }
  "11"
  {
    "name" "custom"
  }
}
