"items"
{
    "npc_dota_hero_pudge"
    {
        "head"
        {
            "__default"          
            {
                "models"
                {
                    "1"
                    {
                        "model" "models/items/pudge/blackdeath_head_s3/blackdeath_head_s3.vmdl"
                    }
                }
            } 
            "pudge_arcana"          
            {
                "models"
                {
                    "1"
                    {
                        "model"         "models/heroes/butcher/pudge_dark_apprentice_hood.vmdl"
                    } 
                }

                "particles"
                {
                    "1" 
                    {
                        "particle"                  "particles/econ/items/rubick/rubick_puppet_master/rubick_head_puppet_ambient_eye.vpcf"

                        "ControlPoints"
                        {
                            "0"
                            {
                                "attach_point"      "attach_eye_l"
                            }
                            "1"
                            {
                                "attach_point"      "attach_eye_l"
                            }
                            "2"
                            {
                                "attach_point"      "attach_eye_l"
                            }
                        }
                    }
                    "2" 
                    {
                        "particle"                  "particles/econ/items/rubick/rubick_puppet_master/rubick_head_puppet_ambient_eye.vpcf"

                        "ControlPoints"
                        {
                            "0"
                            {
                                "attach_point"      "attach_eye_r"
                            }
                            "1"
                            {
                                "attach_point"      "attach_eye_r"
                            }
                            "2"
                            {
                                "attach_point"      "attach_eye_r"
                            }
                        }
                    }
                }
            } 
            "pudge_hood"          
            {
                "models"
                {
                    "1"
                    {
                        "model"         "models/items/pudge/hood_of_defiance.vmdl"              
                    }
                }
            } 
            "rotten_stache"          
            {
                "models"
                {
                    "1"
                    {
                        "model"         "models/items/pudge/combover/combover.vmdl"              
                    }
                }
            } 
        }
        "weapon"
        {
            "__default"          
            {
                "models"
                {
                    "1"
                    {
                        "model" "models/heroes/pudge/righthook.vmdl"
                    }        
                }
            }
            "pudge_hook_gharpoon"          
            {
                "models"
                {
                    "1"
                    {
                        "model"         "models/items/pudge/pudge_skeleton_hook.vmdl"              
                    }
                }
            } 
            "scorching_talon"          
            {
                "models"
                {
                    "1"
                    {
                        "model"         "models/items/pudge/scorching_talon/scorching_talon.vmdl"    
                        "particles"      
                        {
                            "1"
                            {
                                "particle"  "particles/econ/items/pudge/pudge_scorching_talon/pudge_scorching_talon_ambient.vpcf"        
                            }
                        }  
                    }
                }
            }  
        }
        "arm"
        {
            "__default"          
            {
                "models"
                {
                    "1"
                    {
                        "model" "models/heroes/pudge/leftarm.vmdl"
                    }
                }
            } 
            "pudge_golden_octopus_hand"          
            {
                "models"
                {
                    "1"
                    {
                        "model"         "models/items/pudge/immortal_arm/immortal_arm.vmdl"   
                        "material"      "1" 
                        "particles"      
                        {
                            "1"
                            {
                                "particle"  "particles/econ/items/pudge/pudge_immortal_arm/pudge_immortal_arm_ambient_gold.vpcf"        
                            }
                        }            
                    }
                }
            } 
            "pudge_octopus_hand"          
            {
                "models"
                {
                    "1"
                    {
                        "model"         "models/items/pudge/immortal_arm/immortal_arm.vmdl"      
                        "particles"      
                        {
                            "1"
                            {
                                "particle"  "particles/econ/items/pudge/pudge_immortal_arm/pudge_immortal_arm_ambient.vpcf"        
                            }
                        }      
                    }
                }
            } 
        }
        "offhand"
        {
            "__default"          
            {
                "models"
                {
                    "1"
                    {
                        "model"     "models/items/pudge/blackdeath_offhand_s1/blackdeath_offhand_s1.vmdl"
                    }
                }
            }
            "nurgles_plague"
            {
                "models"
                {
                    "1"
                    {
                        "model" "models/items/pudge/plague_doctor_offhand/plague_doctor_offhand.vmdl"
                    }
                    "2"
                    {
                        "model" "models/items/pudge/plague_doctor_shoulder/plague_doctor_shoulder.vmdl"
                    }
                }
                "particles"
                {
                    "1" 
                    {
                        "particle"          "particles/econ/events/ti8/radiance_owner_ti8.vpcf"
                    }
                }
            }
            "champion_of_nurgle"
            {
                "models"
                {
                    "1"
                    {
                        "model" "models/items/pudge/pudge_lord_of_decay_off_hand/pudge_lord_of_decay_off_hand.vmdl"
                    }                
                }
            }  
        }
        "back"
        {
            "__default"          
            {
                "models"
                {
                    "1"
                    {
                        "model"     "models/items/pudge/demon_queller_back/demon_queller_back.vmdl"
                    }
                }
            } 
            "roadhog"
            {
                "model"         "models/heroes/butcher/roadhog/roadhog.vmdl"
            }
            "pudge_vessels_of_eternity"          
            {
                "model"         "models/items/pudge/arcana/pudge_arcana_base.vmdl"

                "models"
                {
                    "1"
                    {
                        "model"         "models/items/pudge/arcana/pudge_arcana_back.vmdl"
                        "particles"   
                        {
                            "1"
                            {
                                "particle"  "particles/econ/items/pudge/pudge_arcana/pudge_arcana_red_back_ambient.vpcf"
                            }
                        }
                    }
                }
                "particles"
                {
                    "1" 
                    {
                        "particle"                  "particles/econ/items/pudge/pudge_deep_sea_abomination_back/pudge_deep_sea_back_ambient.vpcf"
                        
                        "ControlPoints"
                        {
                            "0"
                            {
                                "attach_point"      "attach_eye_l"
                            }
                            "1"
                            {
                                "attach_point"      "attach_attack1"
                            }
                        }
                    }
                    "2" 
                    {
                        "particle"                  "particles/econ/items/pudge/pudge_deep_sea_abomination_back/pudge_deep_sea_back_ambient.vpcf"

                        "ControlPoints"
                        {
                            "0"
                            {
                                "attach_point"      "attach_eye_r"
                            }
                            "1"
                            {
                                "attach_point"      "attach_attack2"
                            }
                        }
                    }
                }
            } 
        }
    }
    "npc_dota_hero_zuus"
    {
        "armor"
        {
            "__default"          
            {
                "models"
                {
                    "1"
                    {
                        "model" "models/items/zuus/the_return_of_the_king_of_gods_head/the_return_of_the_king_of_gods_head_style1.vmdl"
                    }
                    "2"
                    {
                        "model" "models/items/zuus/the_return_of_the_king_of_gods_belt/the_return_of_the_king_of_gods_belt.vmdl"
                    }
                    "3"
                    {
                        "model" "models/items/zuus/the_return_of_the_king_of_gods_back/the_return_of_the_king_of_gods_back.vmdl"
                    }
                    "4"
                    {
                        "model" "models/items/zuus/the_return_of_the_king_of_gods_arms/the_return_of_the_king_of_gods_arms.vmdl"
                    }
                    "5"
                    {
                        "model" "models/items/zuus/lord_of_heaven_back/lord_of_heaven_back.vmdl"
                    }
                }
            }
            "zeus_tempest_helmet"          
            {
                "models"
                {
                    "1"
                    {
                        "model"         "models/heroes/zeus/zeus_hair_arcana.vmdl"
                    }
                    "2"
                    {
                        "model"         "models/items/zuus/the_return_of_the_king_of_gods_belt/the_return_of_the_king_of_gods_belt.vmdl"
                    }
                    "3"
                    {
                        "model"         "models/items/zuus/the_return_of_the_king_of_gods_back/the_return_of_the_king_of_gods_back.vmdl"
                    }
                    "4"
                    {
                        "model"         "models/items/zuus/the_return_of_the_king_of_gods_arms/the_return_of_the_king_of_gods_arms.vmdl"
                    }
                    "5"
                    {
                        "model"         "models/items/zuus/lord_of_heaven_back/lord_of_heaven_back.vmdl"
                    }   
                }
            }  
            "zeus_lighning"          
            {
                "model"                "models/heroes/zeus/zeus_arcana.vmdl"
                "models"
                {
                    "1"
                    {
                        "model"         "models/heroes/zeus/zeus_hair_arcana.vmdl"
                        "particles"
                        {
                            "1"
                            {
                                "particle"      "particles/econ/items/axe/axe_helm_shoutmask/axe_beserkers_call_buff_shout_mask_eye.vpcf"
                                "ControlPoints"
                                {
                                    "0" "attach_eye_r"
                                }
                            }
                            "2"
                            {
                                "particle"      "particles/econ/items/axe/axe_helm_shoutmask/axe_beserkers_call_buff_shout_mask_eye.vpcf"
                                "ControlPoints"
                                {
                                    "0" "attach_eye_l"
                                }
                            }
                        }
                    }
                    "2"
                    {
                        "model"         "models/heroes/hero_zeus/zeus_immortal_armor.vmdl"
                    }
                    "3"
                    {
                        "model"         "models/heroes/hero_zeus/zeus_immortal_belt.vmdl"
                    }
                    "4"
                    {
                        "model"         "models/heroes/hero_zeus/zeus_immortal_shoulder.vmdl"
                    }
                }
                "modifiers"
                {
                    "1"
                    {
                        "modifier"          "modifier_zuus_immortal"
                        "modifier_path"     "modifiers/modifier_zuus_immortal.lua"
                    }
                }
                "particles"
                {
                    "1" 
                    {
                        "particle"                  "particles/econ/items/pudge/pudge_deep_sea_abomination_back/pudge_deep_sea_back_ambient.vpcf"
                        
                        "ControlPoints"
                        {
                            "0"
                            {
                                "attach_point"      "attach_eye_l"
                            }
                            "1"
                            {
                                "attach_point"      "attach_attack1"
                            }
                        }
                    }
                    "2" 
                    {
                        "particle"                  "particles/econ/items/pudge/pudge_deep_sea_abomination_back/pudge_deep_sea_back_ambient.vpcf"

                        "ControlPoints"
                        {
                            "0"
                            {
                                "attach_point"      "attach_eye_r"
                            }
                            "1"
                            {
                                "attach_point"      "attach_attack2"
                            }
                        }
                    }
                }
            }  
        }
        "weapon"
        {
            "god_of_thunder"
            {
                "models"
                {
                    "1"
                    {
                        "model"         "models/items/zeus/lightning_weapon/zuus_lightning_weapon.vmdl"
                        "particles"   
                        {
                            "1"
                            {
                                "particle"  "particles/econ/items/zeus/lightning_weapon_fx/zues_immortal_lightning_weapon.vpcf"
                            }
                        }
                    }
                }
            }
        }
        "bracers"
        {
            "aegis_of_the_immortal"
            {
                "models"
                {
                    "1"
                    {
                        "model"         "models/items/zeus/zeus_ti8_immortal_arms/zeus_ti8_immortal_arms.vmdl"
                        "particles"   
                        {
                            "1"
                            {
                                "particle"  "particles/econ/items/zeus/zeus_ti8_immortal_arms/zeus_ti8_immortal_ambient.vpcf"
                            }
                        }
                    }
                }
            }
        }
    }
    "npc_dota_hero_terrorblade"
    {
        "weapon"
        {
            "galactus_absolute_nulifier"
            {
                "models"
                {
                    "1"
                    {
                        "model"         "models/items/doom/herald_khorne_weapon_alt/herald_khorne_weapon_alt.vmdl"
                    }       
                }
            }
            "demon_shard"
            {
                "models"
                {
                    "1"
                    {
                        "model"         "models/items/doom/demonshard_weapon/demonshard_weapon.vmdl"
                    }       
                }
            }
        }
        "offhand"
        {
            "seed_of_ambitions"
            {
                "models"
                {
                    "1"
                    {
                        "model"         "models/items/doom/doom_ti8_immortal_arms/doom_ti8_immortal_arms.vmdl"
                        "particles"
                        {
                            "1"
                            {
                                "particle"      "particles/econ/items/doom/doom_ti8_immortal_arms/doom_ti8_immortal_ambient.vpcf"
                            }
                        }
                    }       
                }
                "spells"
                {
                    "Ability6"
                    {
                        "AbilityTextureName"    "custom/galactus_seed_of_ambition"
                    }
                }
                "modifiers"
                {
                    "1"
                    {
                        "modifier"          "modifier_galactus_seed_of_ambition"
                        "modifier_path"     "modifiers/modifier_galactus_seed_of_ambition.lua"
                    }
                }
            }
        }      
    }
    "npc_dota_hero_razor"
    {
        "armor"
        {
            "__default"
            {
                "particles"
                {
                    "1" 
                    {
                        "particle"                  "particles/hero_zoom/zoom_ambient.vpcf"
                        
                        "ControlPoints"
                        {
                            "0"
                            {
                                "attach_point"      "attach_hitloc"
                            }
                        }
                    }
                }
            }
             "speed_wraith"
            {
                "model"         "models/heroes/hero_zoom/speed_wraith/blackflash.vmdl"

                "particles"
                {
                    "1" 
                    {
                        "particle"                  "particles/econ/items/bounty_hunter/bounty_hunter_ursine/bounty_hunter_usrine_eyes_r.vpcf"
                        
                        "ControlPoints"
                        {
                            "0"
                            {
                                "attach_point"      "attach_eye_r"
                            }
                            "1"
                            {
                                "attach_point"      "attach_eye_r"
                            }
                        }
                    }
                    "2" 
                    {
                        "particle"                  "particles/econ/items/bounty_hunter/bounty_hunter_ursine/bounty_hunter_usrine_eyes_r.vpcf"

                        "ControlPoints"
                        {
                            "0"
                            {
                                "attach_point"      "attach_eye_l"
                            }
                            "1"
                            {
                                "attach_point"      "attach_eye_l"
                            }
                        }
                    }
                }

                "spells"
                {
                    "Ability6"
                    {
                        "AbilityTextureName"    "custom/bh_relativistic_run"
                    }
                }

                "modifiers"
                {
                    "1"
                    {
                        "modifier"          "modifier_zoom_arcana"
                        "modifier_path"     "modifiers/modifier_zoom_arcana.lua"
                    }
                }
            }
            "stygians_kolyaska"          
            {
                "model"         "models/heroes/hero_zoom/zoom_whellchair/zoom.vmdl"

                "models"
                {
                    "1"
                    {
                        "model"         "models/heroes/hero_zoom/zoom_whellchair/whellchair/wheelchair.vmdl"
                    }
                }
                "particles"
                {
                    "1" 
                    {
                        "particle"                  "particles/econ/items/bounty_hunter/bounty_hunter_ursine/bounty_hunter_usrine_eyes_r.vpcf"
                        
                        "ControlPoints"
                        {
                            "0"
                            {
                                "attach_point"      "attach_eye_r"
                            }
                            "1"
                            {
                                "attach_point"      "attach_eye_r"
                            }
                        }
                    }
                    "2" 
                    {
                        "particle"                  "particles/econ/items/bounty_hunter/bounty_hunter_ursine/bounty_hunter_usrine_eyes_r.vpcf"

                        "ControlPoints"
                        {
                            "0"
                            {
                                "attach_point"      "attach_eye_l"
                            }
                            "1"
                            {
                                "attach_point"      "attach_eye_l"
                            }
                        }
                    }
                }
                "modifiers"
                {
                    "1"
                    {
                        "modifier"          "modifier_zoom_kalyaska"
                        "modifier_path"     "modifiers/modifier_zoom_kalyaska.lua"
                    }
                }
                "spells"
                {
                    "Ability6"
                    {
                        "AbilityTextureName"    "custom/stygian_kolyaska_charge_of_darkness"
                    }
                }
            } 
            "golden_wheelchair"          
            {
                "model"         "models/heroes/hero_zoom/zoom_whellchair/zoom.vmdl"
                "models"
                {
                    "1"
                    {
                        "model"         "models/heroes/hero_zoom/zoom_whellchair/whellchair/wheelchair.vmdl"
                        "material"      "gold"
                        "particles"
                        {
                            "1"
                            {
                                "particle"      "particles/golden_wheelchair.vpcf"
                                "ControlPoints"
                                {
                                    "0"         "attach_chair"
                                    "2"         "attach_chair"
                                }
                            }
                        }
                    }
                }
                "particles"
                {
                    "1" 
                    {
                        "particle"                  "particles/econ/items/bounty_hunter/bounty_hunter_ursine/bounty_hunter_usrine_eyes_r.vpcf"
                        
                        "ControlPoints"
                        {
                            "0"
                            {
                                "attach_point"      "attach_eye_r"
                            }
                            "1"
                            {
                                "attach_point"      "attach_eye_r"
                            }
                        }
                    }
                    "2" 
                    {
                        "particle"                  "particles/econ/items/bounty_hunter/bounty_hunter_ursine/bounty_hunter_usrine_eyes_r.vpcf"

                        "ControlPoints"
                        {
                            "0"
                            {
                                "attach_point"      "attach_eye_l"
                            }
                            "1"
                            {
                                "attach_point"      "attach_eye_l"
                            }
                        }
                    }
                }
                "modifiers"
                {
                    "1"
                    {
                        "modifier"          "modifier_zoom_kalyaska_gold"
                        "modifier_path"     "modifiers/modifier_zoom_kalyaska_gold.lua"
                    }
                }    
                "material"      "gold"         
            } 
        }
    }
    "npc_dota_hero_sniper"
    {
        "weapon"
        {
            "__default"
            {
                "models"
                {
                    "1"
                    {
                        "model"     "models/heroes/hero_racoon/weapon/weapon.vmdl"
                    }
                }          
            }
             "devastator"
            {
                "models"
                {
                    "1"
                    {
                        "model"     "models/heroes/hero_racoon/econs/devastator_x9000.vmdl"
                    }
                }   
                "modifiers"
                {
                    "1"
                    {
                        "modifier"          "modifier_rocket_devastator"
                        "modifier_path"     "modifiers/modifier_rocket_devastator.lua"
                    }
                }
            }
        }
    }
    "npc_dota_hero_juggernaut"
    {
        "weapon"
        {
            "__default"          
            {
                "models"
                {      
                    "1"
                    {
                        "model" "models/heroes/hero_samurai/samurai_weapon.vmdl"
                    }
                }
            } 
            "kantusa_the_script_sword"          
            {
                "models"
                {        
                    "1"
                    {
                        "model" "models/heroes/hero_samurai/samurai_kantusa.vmdl"
                    }
                }
            } 
            "atomic_samurai_frost_arcana"
            {
                "models"
                {
                    "1"
                    {
                        "model" "models/heroes/hero_samurai/samurai_frost_arcana/samurai_frostmourne.vmdl"
                    }
                    "2"
                    {
                        "model" "models/heroes/hero_samurai/samurai_frost_arcana/samurai_ghostmask.vmdl"
                    }
                }
                "particles"
                {
                    "1" 
                    {
                        "particle"          "particles/units/heroes/hero_abaddon/abaddon_ambient.vpcf"
                        "ControlPoints"
                        {
                            "0"
                            {
                                "attach_point"      "attach_hitloc"
                            }
                            "1"
                            {
                                "attach_point"      "attach_hitloc"
                            }
                            "2"
                            {
                                "attach_point"      "attach_hitloc"
                            }
                        }
                    }
                    "2" 
                    {
                        "particle"          "particles/hero_arthas/arthas_eyes.vpcf"
                        "ControlPoints"
                        {
                            "0"
                            {
                                "attach_point"      "attach_eye_l"
                            }                    
                        }
                    }
                    "3" 
                    {
                        "particle"          "particles/hero_arthas/arthas_eyes.vpcf"
                        "ControlPoints"
                        {
                            "0"
                            {
                                "attach_point"      "attach_eye_r"
                            }                    
                        }
                    }
                    "4" 
                    {
                        "particle"          "particles/world_shrine/radiant_shrine_regen.vpcf"
                        "ControlPoints"
                        {
                            "0"
                            {
                                "attach_point"      "attach_hitloc"
                            }                    
                        }
                    }
                    "5" 
                    {
                        "particle"          "particles/econ/items/juggernaut/jugg_arcana/juggernaut_arcana_ambient.vpcf"
                        "ControlPoints"
                        {
                            "0"
                            {
                                "attach_point"      "attach_tail"
                            }      
                            "1"
                            {
                                "attach_point"      "attach_tail"
                            }
                            "3"
                            {
                                "attach_point"      "attach_eye_l"
                            }
                            "4"
                            {
                                "attach_point"      "attach_eye_r"
                            }
                            "5"
                            {
                                "attach_point"      "attach_tail"
                            }              
                        }
                    }
                }
                "modifiers"
                {
                    "1"
                    {
                        "modifier"          "modifier_daredevil_arcana"
                        "modifier_path"     "modifiers/modifier_daredevil_arcana.lua"
                    }
                }
            }
            "legacy_of_blast_gold"          
            {      
                "models"
                {
                    "1"
                    {
                        "model"         "models/heroes/hero_atomic_samurai/legacy_of_blast/blast_sword.vmdl"
                        "material"      "gold"
                        "particles"   
                        {
                            "1"
                            {
                                "particle"      "particles/hero_samurai/legacy_sword.vpcf"
                                ///"ControlPoints"
                                //{
                                //    "0"         "attach_weapon"
                                ///}
                            }
                        }
                    }     
                }
                "modifiers"
                {
                    "1"
                    {
                        "modifier"          "modifier_legacy_of_blast_gold"
                        "modifier_path"     "modifiers/modifier_legacy_of_blast_gold.lua"
                    }
                }
                "spells"
                {
                    "Ability1"
                    {
                        "AbilityTextureName"    "custom/legacy_of_blast_gold"
                    }
                }
            } 
            "legacy_of_blast"          
            {
                "models"
                {
                "1"
                    {
                        "model"         "models/heroes/hero_atomic_samurai/legacy_of_blast/blast_sword.vmdl"                
                    }
                }
            } 
            "samurai_sword_od_darkness"          
            {
                "models"
                {
                    "1"
                    {
                        "model"         "models/heroes/hero_samurai/samurai_blade_of_darkness/blade_of_darkness.vmdl"    
                        "particles"   
                        {
                            "1"
                            {
                                "particle"      "particles/hero_samurai/custom_sword_ambient_a.vpcf"
                            }   
                            "2"
                            {
                                "particle"      "particles/hero_samurai/custom_sword_ambient_b.vpcf"
                            }     
                        }            
                    }
                }
                "particles"
                {
                    "1" 
                    {
                        "particle"          "particles/econ/courier/courier_crystal_rift/courier_ambient_crystal_rift.vpcf"                  
                    }
                }
            } 
        }
        "head"          
        {
            "__default"          
            {
                "models"
                {      
                    "1"
                    {
                        "model" "models/heroes/hero_samurai/samurai_hat.vmdl"
                    }
                }
            }
            "samurai_ancestors" 
            {
                "models"
                {
                    "1"
                    {
                        "model"         "models/samurai/samurai_extraordinary_helmet.vmdl"
                        "particles"   
                        {
                            "1"
                            {
                                "particle"      "particles/hero_samurai/extroordinary_helmet_head.vpcf"
                            }                 
                        }
                    }      
                }
                "modifiers"
                {
                    "1"
                    {
                        "modifier"          "modifier_samurai_ancestors"
                        "modifier_path"     "modifiers/modifier_samurai_ancestors.lua"
                    }
                }
                "spells"
                {
                    "Ability6"
                    {
                        "AbilityTextureName"    "custom/samurai_omnislash_helmet"
                    }
                }
            }
        } 
    }
    "npc_dota_hero_axe"
    {
        "other"
        {
            "axe_blink"
            {
                "models"
                {
                    "1"
                    {
                        "model"     "models/items/axe/generic_blinkdag/generic_blinkdag.vmdl"
                    }
                }
            }
        }
        "head" 
        {
            "__default"
            {
                "models"
                {
                    "1"
                    {
                        "model"     "models/items/axe/armor_of_the_wrought_legion_head/armor_of_the_wrought_legion_head.vmdl"
                    }
                }   
            }
            "rulk_mask"
            {
                "models"
                {
                    "1"
                    {
                        "model"     "models/items/axe/shout_mask/shout_mask.vmdl"
                    }
                }   
            }
            "golden_rulk_mask"
            {
                "models"
                {
                    "1"
                    {
                        "model"     "models/items/axe/shout_mask/shout_mask.vmdl"
                        "particles"   
                        {
                            "1"
                            {
                                "particle"      "particles/econ/items/dazzle/dazzle_ti6_gold/dazzle_ti6_gold_ambient.vpcf"
                                "ControlPoints"
                                {
                                    "0"         "attach_mouth"
                                    "1"         "attach_mouth"
                                    "2"         "attach_mouth"
                                    "3"         "attach_mouth"
                                    "4"         "attach_mouth"
                                }
                            }
                        }
                    }
                }   
            }
            "ravager_mask"
            {
                "models"
                {
                    "1"
                    {
                        "model"     "models/items/axe/harbingerwar_head/harbingerwar_head.vmdl"                  
                    }
                }   
            }
            "axe_executor"
            {
                "models"
                {
                    "1"
                    {
                        "model"     "models/items/axe/hood_executioner.vmdl"                  
                    }
                }   
            }
        }
        "weapon"
        {
            "__default"
            {
                "models"
                {
                    "1"
                    {
                        "model"     "models/items/axe/armor_of_the_wrought_legion_weapon/armor_of_the_wrought_legion_weapon.vmdl"                  
                    }
                }  
            }
            "axe_of_phractos"
            {
                "models"
                {
                    "1"
                    {
                        "model"     "models/items/axe/axe_practos_weapon/axe_practos_weapon.vmdl"                  
                    }
                }   
            }
        }
        "cape"
        {
            "__default"
            {
                "models"
                {
                    "1"
                    {
                        "model"     "models/items/axe/blacksmith_cape.vmdl"                  
                    }
                }  
            }
            "molten_cape"
            {
                "models"
                {
                    "1"
                    {
                        "model"     "models/items/axe/axe_cape/axe_cape.vmdl"
                        "particles"   
                        {
                            "1"
                            {
                                "particle"      "particles/econ/items/axe/axe_cinder/axe_cinder_ambient_alt.vpcf"                           
                            }
                        }
                    }
                }
            }
        }
        "armor"
        {
            "__default"
            {
                "models"
                {
                    "1"
                    {
                        "model"     "models/items/axe/armor_of_the_wrought_legion_armor/armor_of_the_wrought_legion_armor.vmdl"                  
                    }
                }  
            }
        }
        "belt"
        {
            
        }
    }
    "npc_dota_hero_arc_warden"
    {
        "head" 
        {
            "cowl_of_the_first_ways"
            {
                "models"
                {
                    "1"
                    {
                        "model"     "models/items/arc_warden/arctic_warden_shoulder/arctic_warden_head.vmdl"
                    }
                }   
            }
        }
    }
    "npc_dota_hero_faceless_void"
    {
        "head" 
        {
            "__default"
            {
                "models"
                {
                    "1"
                    {
                        "model" "models/heroes/faceless_void/faceless_void_head.vmdl"
                    }
                }
            }
        }
        "weapon"
        {
            "__default"
            {
                "models"
                {
                    "1"
                    {
                        "model" "models/heroes/faceless_void/faceless_void_weapon.vmdl"
                    }
                }
            }
            "byonder_arcana"
            {
                "models"
                {
                    "1"
                    {
                        "model"         "models/items/faceless_void/mace_of_aeons/mace_of_aeons.vmdl"
                        "particles"   
                        {
                            "1"
                            {
                                "particle"      "particles/econ/items/faceless_void/faceless_void_mace_of_aeons/fv_ambient_mace_aeons.vpcf"
                            }
                        }
                    }     
                    "2"
                    {
                        "model"         "models/items/faceless_void/jewel_of_aeons/jewel_of_aeons.vmdl"
                        "particles"   
                        {
                            "1"
                            {
                                "particle"      "particles/econ/items/faceless_void/faceless_void_jewel_of_aeons/fv_core_ambient_aeons.vpcf"
                                "ControlPoints"
                                {
                                    "0"         "attach_shoulder_l"
                                    "2"         "attach_shoulder_l"
                                }
                            }
                            "2"
                            {
                                "particle"      "particles/econ/items/faceless_void/faceless_void_jewel_of_aeons/fv_ambient_aeons.vpcf"
                            }
                        }
                    }         
                }

                "modifiers"
                {
                    "1"
                    {
                        "modifier"          "modifier_arcana"
                        "modifier_path"     "modifiers/modifier_arcana.lua"
                    }
                }
            }
            "battle_fury"
            {
                "models"
                {
                    "1"
                    {
                        "model" "models/items/faceless_void/battlefury/battlefury.vmdl"
                    }
                }
            }
            "masterpice"
            {
                "models"
                {
                    "1"
                    {
                        "model" "models/items/faceless_void/voidhammer/voidhammer.vmdl"
                         "particles"   
                        {
                            "1"
                            {
                                "particle"      " particles/econ/items/faceless_void/faceless_void_weapon_voidhammer/faceless_void_weapon_voidhammer.vpcf"
                            }
                        }                     
                    }
                }
            }
        }
        "bracer"
        {
            "__default"
            {
                "models"
                {
                    "1"
                    {
                        "model" "models/heroes/faceless_void/faceless_void_bracer.vmdl"
                    }
                }
            }
            "bracers_of_the_crimson_darkness"
            {
                "models"
                {
                    "1"
                    {
                        "model" "models/items/faceless_void/bracers_of_aeons/bracers_of_aeons.vmdl"
                        "material"      "1"
                        "particles"   
                        {
                            "1"
                            {
                                "particle"      "particles/econ/items/faceless_void/faceless_void_bracers_of_aeons/fv_bracers_of_aeons_red_ambient.vpcf"

                            }
                        }
                    }
                }
            }
        }
        "belt"
        {
            "__default"
            {
                "models"
                {
                    "1"
                    {
                        "model" "models/heroes/faceless_void/faceless_void_belt.vmdl"
                    }
                }
            }
        }
        "taunt"
        {
            "__default"
            {
                "models"
                {
                    "1"
                    {
                        "model" "models/heroes/faceless_void/faceless_void_taunt.vmdl"
                    }
                }
            }
        }
    }
    "npc_dota_hero_spectre"
    {
        "head" 
        {
            "__default"
            {
                "models"
                {
                    "1"
                    {
                        "model" "models/dcu_spectre/spectre_head_final.vmdl"
                    }
                }
            }
        }
        "belt"
        {
            "spectre_armor"
            {
                "models"
                {
                    "1"
                    {
                        "model"         "models/items/silencer/silent_guardian_belt/silent_guardian_belt.vmdl"
                    }         
                }
            }
        }
        "hand"
        {
            "__default"
            {
                "models"
                {
                    "1"
                    {
                        "model" "models/items/silencer/whispertribunal_arms/whispertribunal_arms.vmdl"
                    }
                }
            }
            "hands_of_judgment"
            {
                "models"
                {
                    "1"
                    {
                        "model" "models/items/silencer/bts_final_utterance_arms/bts_final_utterance_arms.vmdl"
                    }
                }
            }
        }
    }
    "npc_dota_hero_nevermore"
    {
        "weapon" 
        {
            "__default"
            {
                "models"
                {
                    "1"
                    {
                        "model" "models/heroes/hero_deadpool/econs/deadpool_sword.vmdl"
                    }
                }
            }
            "the_primal_fear"
            {
                "model"     "models/heroes/hero_atomic_arcana/dante.vmdl"
                "models"
                {
                    "1"
                    {
                        "model" "models/heroes/hero_atomic_arcana/dante_sword.vmdl"
                    }
                }
                "particles"
                {
                    "1" 
                    {
                        "particle"          "particles/econ/items/monkey_king/arcana/monkey_king_arcana_fire_body.vpcf"
                        "ControlPoints"
                        {
                            "0"
                            {
                                "attach_point"      "attach_hitloc"
                            }
                            "3"
                            {
                                "attach_point"      "attach_hitloc"
                            }
                        }
                    }
                }
                "modifiers"
                {
                    "1"
                    {
                        "modifier"          "modifier_dante"
                        "modifier_path"     "modifiers/modifier_dante.lua"
                    }
                }
            }
            "khornes_will_sword"
            {
                "models"
                {
                    "1"
                    {
                        "model" "models/heroes/hero_deadpool/econs/deadpool_khornes_sword.vmdl"
                    }
                }
            }
            "sword_of_the_great_warrior"
            {
                "models"
                {
                    "1"
                    {
                        "model" "models/heroes/hero_deadpool/econs/genji_sword.vmdl"
                        "particles"
                        {
                            "1"
                            {
                                "particle"  "particles/econ/items/genji_sword.vpcf"
                                "ControlPoints"
                                {
                                    "0"     "attach_sword"
                                }
                            }
                        }
                    }
                }
            }
            "the_old_facion"
            {
                "model"     "models/b2/b2.vmdl"
                "models"
                {
                    "1"
                    {
                        "model" "models/b2/weapon/weapon.vmdl"
                    }
                }
                "particles"
                {
                    "1" 
                    {
                        "particle"          "particles/econ/items/monkey_king/arcana/monkey_king_arcana_fire_body.vpcf"
                        "ControlPoints"
                        {
                            "0"
                            {
                                "attach_point"      "attach_hitloc"
                            }
                            "3"
                            {
                                "attach_point"      "attach_hitloc"
                            }
                        }
                    }
                }
                "spells"
                {
                    "Ability6"
                    {
                        "AbilityTextureName"    "custom/the_old_facion_ult"
                    }
                    "Ability3"
                    {
                        "AbilityTextureName"    "custom/the_old_facion_crit"
                    }
                     "Ability1"
                    {
                        "AbilityTextureName"    "custom/the_old_facion_heal"
                    }
                }
                "modifiers"
                {
                    "1"
                    {
                        "modifier"          "modifier_neo_noir"
                        "modifier_path"     "modifiers/modifier_neo_noir.lua"
                    }
                }
            }
        }
    }
    "npc_dota_hero_weaver"
    {
        "head"
        {
             "__default"
            {
                "particles"
                {
                    "1" 
                    {
                        "particle"          "particles/econ/items/ancient_apparition/aa_blast_ti_5/aa_ti5_eye.vpcf"
                        "ControlPoints"
                        {
                            "0"
                            {
                                "attach_point"      "attach_eye_l"
                            }
                            "1"
                            {
                                "attach_point"      "attach_eye_l"
                            }
                            "2"
                            {
                                "attach_point"      "attach_eye_l"
                            }
                        }
                    }
                    "2" 
                    {
                        "particle"          "particles/econ/items/ancient_apparition/aa_blast_ti_5/aa_ti5_eye.vpcf"
                        "ControlPoints"
                        {
                            "0"
                            {
                                "attach_point"      "attach_eye_r"
                            }
                            "1"
                            {
                                "attach_point"      "attach_eye_r"
                            }
                            "2"
                            {
                                "attach_point"      "attach_eye_r"
                            }
                        }
                    }
                }
            }
        }
        "weapon" 
        {
            "doomsday_clock"
            {
                "model"     "models/heroes/hero_reverse_flash_arcana/reverseflash_arcana.vmdl"
                "ambient"   "Hero_Razor.IdleLoop"
                "modifiers"
                {
                    "1"
                    {
                        "modifier"          "modifier_doomsday_clock"
                        "modifier_path"     "modifiers/modifier_doomsday_clock.lua"
                    }
                }
            }
        }
    }
    "npc_dota_hero_invoker"
    {
        "__head"
        {
            "__default"
            {
                "models"
                {
                    "1"
                    {
                        "model"        "models/collector/collector_head.vmdl"
                    }
                }
            }
        }
        "head"
        {
           
        }
        "armor"
        {
            "alma"
            {
                "model"                             "models/heroes/hero_collector/collector_arcana/collector.vmdl"
                "particles"
                {
                    "1" 
                    {
                        "particle"                  "particles/econ/courier/courier_golden_roshan/golden_roshan_eyes.vpcf"
                        "ControlPoints"
                        {
                            "0"
                            {
                                "attach_point"      "attach_eye_r"
                            }
                            "1"
                            {
                                "attach_point"      "attach_eye_l"
                            }
                        }
                    }
                }
                "modifiers"
                {
                    "1"
                    {
                        "modifier"          "modifier_alma"
                        "modifier_path"     "modifiers/modifier_alma.lua"
                    }
                }
            }
            "the_eternal_master"
            {
                "models"
                {
                    "1"
                    {
                        "model"         "models/items/invoker/covenant_of_the_depths_belt_v2/covenant_of_the_depths_belt_v2.vmdl"                          
                    }
                    "2"
                    {
                        "model"         "models/items/invoker/dark_artistry/dark_artistry_shoulder_model.vmdl"                          
                    }
                    "3"
                    {
                        "model"         "models/items/invoker/covenant_of_the_depths_shoulder/covenant_of_the_depths_shoulder.vmdl"                          
                    }
                    "4"
                    {
                        "model"         "models/items/invoker/dark_artistry/dark_artistry_cape_model.vmdl"                          
                    }
                }
                "particles"
                {
                    "1" 
                    {
                        "particle"                  "particles/units/heroes/hero_bane/bane_nightmare_inkblots.vpcf"
                    }
                    "2" 
                    {
                        "particle"                  "particles/units/heroes/hero_bane/bane_nightmare_inkblots_thick.vpcf"
                    }
                    "3" 
                    {
                        "particle"                  "particles/units/heroes/hero_bane/bane_nightmare_worms.vpcf"
                    }
                }
            }
            "fate_meridian"
            {
                "models"
                {
                    "1"
                    {
                        "model"        "models/items/invoker/ti8_invoker_prism_crystal_spellcaster_belt/ti8_invoker_prism_crystal_spellcaster_belt.vmdl"
                    }
                    "2"
                    {
                        "model"        "models/items/invoker/ti8_invoker_prism_crystal_spellcaster_shoulder/ti8_invoker_prism_crystal_spellcaster_shoulder.vmdl"
                    }
                    "3"
                    {
                        "model"        "models/items/invoker/ti8_invoker_prism_crystal_spellcaster_back/ti8_invoker_prism_crystal_spellcaster_back.vmdl"
                    }
                }
            }
        }
        "arms" 
        {
            "collector_gloves_of_elder_one"
            {
                "models"
                {
                    "1"
                    {
                        "model"         "models/items/invoker/immortal_arms_ti7/immortal_arms_ti7.vmdl"    
                        "particles"
                        {
                            "1"
                            {
                                "particle"      "particles/econ/items/invoker/invoker_ti7/invoker_ti7_bracer_ambient.vpcf"   
                                "ControlPoints"
                                {
                                    "0"         "attach_hand_l"
                                    "1"         "attach_hand_r"
                                }                        
                            }
                         
                        }                  
                    }
                }
                "projectile"
                {
                    "particle"              "particles/collector/collector_projectile.vpcf"
                }
            }
        }
    }
    "npc_dota_hero_chaos_knight"
    {
        "effects"
        {
            "__default"
            {
                "particles"
                {
                    "1" 
                    {
                        "particle"                  "particles/hero_ghost_rider/ghost_rider_ambient_1.vpcf"                                       
                    }
                    "2" 
                    {
                        "particle"                  "particles/hero_ghost_rider/ghost_rider_ambient_head.vpcf"

                        "ControlPoints"
                        {
                            "0"
                            {
                                "attach_point"      "attach_head"
                            }
                            "12"
                            {
                                "attach_point"      "attach_head"
                            }
                        }
                    }
                }
            }
        }
        "weapon"
        {
            "__default"
            {
                 "models"
                {
                    "1"
                    {
                        "model"        "models/heroes/hero_ghost_rider/econs/pistol/pistol.vmdl"
                    }
                }
            }
        }
    }
    "npc_dota_hero_sand_king"
    {
        "effects"
        {
            "__default"
            {
                "particles"
                {
                    "1" 
                    {
                        "particle"                  "particles/econ/courier/courier_roshan_frost/courier_roshan_frost_ambient.vpcf"                                       
                    }
                    "2" 
                    {
                        "particle"                  "particles/econ/items/lich/lich_ti8_immortal_arms/lich_ti8_ambient_skull_eye.vpcf"

                        "ControlPoints"
                        {
                            "2"
                            {
                                "attach_point"      "attach_eye_r"
                            }
                            "3"
                            {
                                "attach_point"      "attach_eye_l"
                            }
                        }
                    }
                }
            }
        }
        "weapon"
        {
            "__default"
            {
                 "models"
                {
                    "1"
                    {
                        "model"        "models/heroes/hero_night_king/night_king_sword.vmdl"
                    }
                }
            }
            "ancient_relic"
            {
                 "models"
                {
                    "1"
                    {
                        "model"        "models/heroes/hero_night_king/night_king_ancient_sword.vmdl"
                        "particles"
                        {
                            "1"
                            {
                                "particle"  "particles/econ/courier/courier_wabbit/courier_wabbit_ambient_lvl2.vpcf"
                                "ControlPoints"
                                {
                                    "1"         "attach_sword"
                                    "2"         "attach_sword"
                                    "3"         "attach_sword"
                                    "4"         "attach_sword"
                                }
                            }
                        }
                    }
                }
            }
        }
        "head"
        {
            "__default"
            {
                 "models"
                {
                    "1"
                    {
                        "model"        "models/heroes/hero_night_king/night_king_crown.vmdl"
                    }
                }
            }
        }
        "armor"
        {
            "__default"
            {
                 "models"
                {
                    "1"
                    {
                        "model"        "models/heroes/hero_night_king/night_king_armor.vmdl"
                    }
                }
            }
        }
    }
    "npc_dota_hero_ursa"
    {
        "spine"          
        {
            "__default"          
            {
                "models"
                {      
                    "1"
                    {
                        "model" "models/heroes/ursa/fur.vmdl"
                    }
                }
            }
        } 
        "item"          
        {
            "__default"          
            {
                "models"
                {      
                    "1"
                    {
                        "model" "models/heroes/ursa/skirt.vmdl"
                    }
                }
            }
        } 
        "head"          
        {
            "__default"          
            {
                "models"
                {      
                    "1"
                    {
                        "model" "models/heroes/ursa/helmet.vmdl"
                    }
                }
            }
            "alpine_hat"          
            {
                "models"
                {      
                    "1"
                    {
                        "model" "models/items/ursa/hat_alpine.vmdl"
                    }
                }
            }
            "ursa_devils_helmet"          
            {
                "models"
                {      
                    "1"
                    {
                        "model"                 "models/items/ursa/ti6_ursa_head/ti6_ursa_head.vmdl"
                        "material"              "1"
                        "particles"
                        {
                            "1"
                            {
                                "particle"      "particles/econ/items/ursa/ursa_razorwyrm/ursa_razorwyrm_ambient_eyes.vpcf"
                                "ControlPoints"
                                {
                                    "0"         "attach_eye_l"
                                    "1"         "attach_eye_l"
                                    "2"         "attach_eye_r"
                                }
                            }
                        }
                    }
                }
                "modifiers"
                {
                    "1"
                    {
                        "modifier"          "modifier_ursa_devils_helmet"
                        "modifier_path"     "modifiers/modifier_ursa_devils_helmet.lua"
                    }
                }
            }
        } 
    }
    "npc_dota_hero_alchemist"
    {
        "weapon"          
        {
            "batman_infinity_gauntlet"          
            {
                "models"
                {      
                    "1"
                    {
                        "model"                 "models/heroes/hero_batman/infinity_gauntlet/batman_infinity_gauntlet.vmdl"
                        "particles"
                        {
                            "1"
                            {
                                "particle"      "particles/econ/courier/courier_golden_roshan/golden_roshan_ambient.vpcf"
                            }
                            "2"
                            {
                                "particle"      "particles/econ/courier/courier_beetlejaw/courier_beetlejaw_ambient.vpcf"
                                "ControlPoints"
                                {
                                    "1"         "attach_gem_mind"
                                    "2"         "attach_gem_mind"
                                    "4"         "attach_gem_mind"
                                }
                            }
                            "3"
                            {
                                "particle"      "particles/econ/courier/courier_flopjaw_gold/courier_flopjaw_ambient_gold.vpcf"
                                "ControlPoints"
                                {
                                     "0"         "attach_gem_mind"
                                     "1"         "attach_gem_mind"
                                     "2"         "attach_gem_mind"
                                }
                            }
                        }
                    }
                }
                "modifiers"
                {
                    "1"
                    {
                        "modifier"          "modifier_batman_infinity_gauntlet"
                        "modifier_path"     "modifiers/modifier_batman_infinity_gauntlet.lua"
                    }
                }
            }
        } 
    }
    "npc_dota_hero_kunkka"
    {
        "bracers"          
        {
            "strange_eternal_bracers"          
            {
                "models"
                {      
                    "1"
                    {
                        "model"                 "models/heroes/hero_drstrange/bracers_of_eternity/bracers_of_eternity.vmdl"
                        "particles"
                        {
                            "1"
                            {
                                "particle"      "particles/econ/courier/courier_hermit_crab/hermit_crab_octarine_ambient.vpcf"
                                "ControlPoints"
                                {
                                    "0"         "attach_arm_l"
                                    "1"         "attach_arm_l"
                                }
                            }
                            "2"
                            {
                                "particle"      "particles/econ/courier/courier_hermit_crab/hermit_crab_octarine_ambient.vpcf"
                                "ControlPoints"
                                {
                                    "0"         "attach_arm_r"
                                    "1"         "attach_arm_r"
                                }
                            }
                        }                 
                    }
                }
                "modifiers"
                {
                    "1"
                    {
                        "modifier"          "modifier_strange_eternal_bracers"
                        "modifier_path"     "modifiers/modifier_strange_eternal_bracers.lua"
                    }
                }        
            }
        } 
    }
    "npc_dota_hero_doom_bringer"
    {
        "weapon"          
        {
            "__default"
            {
                 "models"
                {
                    "1"
                    {
                        "model"        "models/heroes/hero_doom/weapon/weapon.vmdl"
                    }
                }
            }
            "doom_melted_sword"          
            {
                "models"
                {      
                    "1"
                    {
                        "model"                 "models/heroes/hero_doom/doom_melted_sword.vmdl"
                        "particles"
                        {
                            "1"
                            {
                                "particle"      "particles/hero_doom/doom_melted_sword_ambient.vpcf"
    
                            }                    
                        }                 
                    }
                }
            }
        } 
    }
    "npc_dota_hero_lycan"
    {
        "__head"
        {
            "__default"
            {
                "models"
                {
                    "1"
                    {
                        "model"         "models/heroes/lycan/lycan_head.vmdl"
                    }
                }
            }
        }
        "belt"
        {
            "__default"
            {
                "models"
                {
                    "1"
                    {
                        "model"         "models/heroes/lycan/lycan_belt.vmdl"
                    }
                }
            }
        }
        "armor"
        {
            "__default"
            {
                "models"
                {
                    "1"
                    {
                        "model"         "models/heroes/lycan/lycan_armor.vmdl"
                    }
                }
            }
             "blood_moon_rising"
            {
                "models"
                {
                    "1"
                    {
                        "model"         "models/items/lycan/blood_moon_hunter_armor/blood_moon_hunter_armor.vmdl"
                    }
                }
            }
        }
        "weapon"          
        {
            "__default"
            {
                 "models"
                {
                    "1"
                    {
                        "model"        "models/heroes/lycan/lycan_blades.vmdl"
                    }
                }
            }
            "wolverine_claws"          
            {
                "models"
                {      
                    "1"
                    {
                        "model"                 "models/items/lycan/blood_moon_hunter_weapon/blood_moon_hunter_weapon.vmdl"
                        "particles"
                        {
                            "1"
                            {
                                "particle"      "particles/econ/items/lycan/blood_moon/lycan_blood_moon_weapon_ambient.vpcf"
    
                            }                    
                        }                 
                    }
                }
            }
        } 
    }
    "npc_dota_hero_life_stealer"
    {
        "arms"
        {
            "__default"
            {
                "models"
                {
                    "1"
                    {
                        "model"         "models/items/lifestealer/ravenous_arms/ravenous_arms.vmdl"
                    }
                }
            }
        }
        "belt"
        {
            "__default"
            {
                "models"
                {
                    "1"
                    {
                        "model"         "models/items/lifestealer/mad_naix_of_the_fury_dungeon_belt/mad_naix_of_the_fury_dungeon_belt.vmdl"
                    }
                }
            }
        }
        "head"
        {
            "__default"
            {
                "models"
                {
                    "1"
                    {
                        "model"         "models/items/lifestealer/ravenous_head/ravenous_head.vmdl"
                    }
                }
            }
            "redrage_crawler_helm"
            {
                "models"
                {
                    "1"
                    {
                        "model"         "models/items/lifestealer/redrage_head/redrage_head.vmdl"
                    }
                }
            }
        }
        "armor"
        {
            "__default"
            {
                "models"
                {
                    "1"
                    {
                        "model"         "models/heroes/lycan/lycan_armor.vmdl"
                    }
                }
            }
            "doomsday_golden_adaptive_armor"
            {
                "models"
                {
                    "1"
                    {
                        "model"         "models/items/lifestealer/immortal_back/lifestealer_immortal_back_rage_golden.vmdl"
                        "particles"
                        {
                            "1"
                            {
                                "particle"          "particles/econ/items/lifestealer/lifestealer_immortal_backbone_gold/lifestealer_immortal_backbone_gold_ambient.vpcf"
                            }
                            "2"
                            {
                                "particle"          "particles/econ/items/lifestealer/lifestealer_immortal_backbone_gold/lifestealer_immortal_backbone_gold_rage_beams.vpcf"
                            }
                        }
                    }
                }
                "particles"
                {
                    "1" 
                    {
                        "particle"                  "particles/econ/items/lifestealer/lifestealer_immortal_backbone_gold/lifestealer_immortal_backbone_gold_rage.vpcf"
                    }           
                }
            }
            "doomsday_adaptive_armor"
            {
                "models"
                {
                    "1"
                    {
                        "model"         "models/items/lifestealer/immortal_back/lifestealer_immortal_back_rage.vmdl"
                        "particles"
                        {
                            "1"
                            {
                                "particle"          "particles/econ/items/lifestealer/lifestealer_immortal_backbone/lifestealer_immortal_backbone_rage_ambient.vpcf"
                            }
                            "2"
                            {
                                "particle"          "particles/econ/items/lifestealer/lifestealer_immortal_backbone/lifestealer_immortal_backbone_rage_beams.vpcf"
                            }
                            "3"
                            {
                                "particle"          "particles/econ/items/lifestealer/lifestealer_immortal_backbone/lifestealer_immortal_backbone_ambient.vpcf"
                            }
                        }
                    }
                }
                "particles"
                {
                    "1" 
                    {
                        "particle"                  "particles/econ/items/lifestealer/lifestealer_immortal_backbone/lifestealer_immortal_backbone_rage.vpcf"
                    }           
                }
            }
        }
    }
    "npc_dota_hero_monkey_king"
    {
        "armor"          
        {
            "__default"          
            {
                "models"
                {      
                    "1"
                    {
                        "model"         "models/heroes/monkey_king/monkey_king_armor.vmdl"
                    }
                }
            }
        } 
        "cape"          
        {
            "__default"          
            {
                "models"
                {      
                    "1"
                    {
                        "model"         "models/heroes/monkey_king/monkey_king_cape.vmdl"
                    }
                }
            }
        } 
        "head"          
        {
            "__default"          
            {
                "models"
                {      
                    "1"
                    {
                        "model"         "models/heroes/monkey_king/monkey_king_hair.vmdl"
                    }
                }
            }
            "monkey_king_crown_of_old_god"          
            {
                "material"              "3"
                "models"
                {      
                    "1"
                    {
                        "model"         "models/items/monkey_king/monkey_king_arcana_head/mesh/monkey_king_arcana.vmdl"
                    }
                }
                "particles"
                {
                    "1" 
                    {
                        "particle"          "particles/econ/items/monkey_king/arcana/monkey_king_arcana_death.vpcf"
                    }
                    "2" 
                    {
                        "particle"          "particles/econ/items/monkey_king/arcana/monkey_king_arcana_crown.vpcf"
                    }        
                }
                "modifiers"
                {
                    "1"
                    {
                        "modifier"          "modifier_daredevil_arcana"
                        "modifier_path"     "modifiers/modifier_daredevil_arcana.lua"
                    }
                }
            }
            "monkey_king_hair_bronze_crown"          
            {
                "models"
                {      
                    "1"
                    {
                        "model"                 "models/items/monkey_king/monkey_king_king_of_the_dark_reef_ti_2017_head/monkey_king_king_of_the_dark_reef_ti_2017_head.vmdl"          
                    }
                }
            }
        }
        "weapon"
        {
            "__default"          
            {
                "models"
                {      
                    "1"
                    {
                        "model"         "models/heroes/monkey_king/monkey_king_base_weapon.vmdl"
                    }
                }
            }
            "monkey_king_hair_bronze_staff"          
            {
                "models"
                {      
                    "1"
                    {
                        "model"         "models/items/monkey_king/monkey_king_king_of_the_dark_reef_ti_2017_weapon/monkey_king_king_of_the_dark_reef_ti_2017_weapon.vmdl"
                    }
                }
            }
            "monkey_king_golden_staff"          
            {
                "models"
                {      
                    "1"
                    {
                        "material"              "2"
                        "model"                 "models/items/monkey_king/monkey_king_immortal_weapon/monkey_king_immortal_weapon.vmdl"
                        "particles"
                        {
                            "1"
                            {
                                "particle"      "particles/econ/items/monkey_king/ti7_weapon/mk_ti7_golden_immortal_weapon_ambient.vpcf"
                            }
                        }
                    }
                }
            }
        } 
    }
    "npc_dota_hero_skywrath_mage"
    {
        "weapon"
        {       
            "saitama_arcana"
            {
                "model"         "models/heroes/hero_sitama/saitama_arcana/saitama_arcana.vmdl"
                "models"
                {
                    "1"
                    {
                        "model"     "models/heroes/hero_sitama/saitama_arcana/saitama_foulfell.vmdl"
                    }
                    "2"
                    {
                        "model"     "models/heroes/hero_sitama/saitama_arcana/saitama_foulfell_offhand.vmdl"
                    }
                    "3"
                    {
                        "model"     "models/items/antimage/ti7_antimage_immortal/ti7_immortal_armor.vmdl"
                        "particles"
                        {
                            "1"
                            {
                                "particle"          "particles/econ/items/antimage/antimage_ti7_golden/antimage_ti7_golden_ambient.vpcf"
                            }
                        }
                    }
                    "4"
                    {
                        "model"     "models/heroes/hero_sitama/saitama_arcana/saitama_foulfell_head.vmdl"
                    }
                }   
                "modifiers"
                {
                    "1"
                    {
                        "modifier"          "modifier_saitama_arcana"
                        "modifier_path"     "modifiers/modifier_saitama_arcana.lua"
                    }
                }
                "particles"
                {
                    "1"
                    {
                        "particle"      "particles/econ/courier/courier_jadehoof_ambient/jadehoof_ambient.vpcf"
                    }
                }
            }
        }
    }
    "npc_dota_hero_miraak"
    {
        "weapon"
        {       
            "__default"
            {
                "models"
                {
                    "1"
                    {
                        "model"     "models/heroes/hero_miraak/econs/sword.vmdl"
                    }                
                }   
                "modifiers"
                {
                    "1"
                    {
                        "modifier"          "modifier_saitama_arcana"
                        "modifier_path"     "modifiers/modifier_saitama_arcana.lua"
                    }
                }
            }
            "whale_blade"
            {
                "models"
                {
                    "1"
                    {
                        "model"     "models/heroes/hero_miraak/econs/miraak_immortal_weapon.vmdl"
                    }                
                }   
                "modifiers"
                {
                    "1"
                    {
                        "modifier"          "modifier_saitama_arcana"
                        "modifier_path"     "modifiers/modifier_saitama_arcana.lua"
                    }
                }
            }
            "emerald_whale_blade"
            {
                "models"
                {
                    "1"
                    {
                        "model"     "models/heroes/hero_miraak/econs/miraak_immortal_weapon.vmdl"
                        "material"  "emerald"
                        "particles"
                        {
                           "1"
                            {
                                "particle"      "particles/econ/items/kunkka/kunkka_weapon_whaleblade_retro/kunkka_weapon_glow_whaleblade_retro_lvl2_ambient.vpcf"
                                "ControlPoints"
                                {
                                    "0"         "attach_weapon" 
                                    "2"         "attach_weapon"
                                    "4"         "attach_weapon"
                                }
                            }
                        }
                    }                
                }   
                "modifiers"
                {
                    "1"
                    {
                        "modifier"          "modifier_saitama_arcana"
                        "modifier_path"     "modifiers/modifier_saitama_arcana.lua"
                    }
                }
            }
        }
    }
    "npc_dota_hero_enigma"
    {
        "bracers"
        {       
            "enigma_bracers"
            {
                "models"
                {
                    "1"
                    {
                        "model"     "models/heroes/hero_infinity/enigma_bracers.vmdl"
                        "particles"
                        {
                            "1"
                            {
                                "particle"          "particles/econ/items/dazzle/dazzle_ti6_gold/dazzle_ti6_gold_ambient.vpcf"
                            }
                            "2"
                            {
                                "particle"          "particles/econ/items/dazzle/dazzle_ti6_gold/dazzle_ti6_gold_ambient.vpcf"
                            }
                        }
                    }                
                }   
            }
        }
        "armor"
        {       
            "enigma_singularity"
            {
                "models"
                {
                    "1"
                    {
                        "model"     "models/items/enigma/absolute_zero_updated_armour/absolute_zero_updated_armour.vmdl"
                        "particles"
                        {
                            "1"
                            {
                                "particle"          "particles/econ/items/enigma/enigma_absolute_armour/enigma_absolute_armour_ambient.vpcf"
                            }
                            "2"
                            {
                                "particle"          "particles/econ/items/enigma/enigma_absolute_arms/enigma_absolute_arms_ambient.vpcf"
                            }
                        }
                    }                
                }
                "modifiers"
                {
                    "1"
                    {
                        "modifier"          "modifier_arcana"
                        "modifier_path"     "modifiers/modifier_arcana.lua"
                    }
                }   
            }
        }
        "head"
        {       
            "enigma_ancient"
            {
                "models"
                {
                    "1"
                    {
                        "model"     "models/items/enigma/world_chasm/world_chasm.vmdl"
                    }                
                }   
            }
        }
    }
    "npc_dota_hero_ember_spirit"
    {
        "armor"          
        {
            "osiris_vestments"          
            {
                "model"                 "models/heroes/hero_goldengod/osiris_legacy/golden_god_arcana.vmdl"
                "modifiers"
                {
                    "1"
                    {
                        "modifier"          "modifier_arcana"
                        "modifier_path"     "modifiers/modifier_arcana.lua"
                    }
                }
                 "particles"
                {
                    "1" 
                    {
                        "particle"          "particles/goldengod/goldengod_ambient.vpcf"
                        "ControlPoints"
                        {
                            "0"
                            {
                                "attach_point"      "attach_hitloc"
                            }
                            "1"
                            {
                                "attach_point"      "attach_hitloc"
                            }
                            "3"
                            {
                                "attach_point"      "attach_hitloc"
                            }
                        }
                    }
                    "2" 
                    {
                        "particle"          "particles/goldengod/goldengod_ambient_hands.vpcf"
                        "ControlPoints"
                        {
                            "0"
                            {
                                "attach_point"      "attach_attack1"
                            }
                            "1"
                            {
                                "attach_point"      "attach_attack1"
                            }
                        }
                    }
                    "3" 
                    {
                        "particle"          "particles/goldengod/goldengod_ambient_inner.vpcf"
                        "ControlPoints"
                        {
                            "0"
                            {
                                "attach_point"      "attach_hitloc"
                            }
                            "1"
                            {
                                "attach_point"      "attach_hitloc"
                            }
                        }
                    }      
                    "4" 
                    {
                        "particle"          "particles/econ/items/bounty_hunter/bounty_hunter_ursine/bounty_hunter_usrine_eyes.vpcf"
                        "ControlPoints"
                        {
                            "0"
                            {
                                "attach_point"      "attach_eye_l"
                            }
                            "1"
                            {
                                "attach_point"      "attach_eye_r"
                            }
                            "2"
                            {
                                "attach_point"      "attach_hitloc"
                            }
                        }
                    }    
                }
            }
        } 
        "weapon"
        {
            "rapiers_of_the_sun_god"          
            {
                "models"
                {      
                    "1"
                    {
                        "model"                 "models/items/ember_spirit/rapier_burning_god_weapon/rapier_burning_god_weapon.vmdl"
                        "particles"
                        {
                            "1"
                            {
                                "particle"      "particles/econ/items/ember_spirit/ember_spirit_burning_god_primary/ember_spirit_ambient_burning_god_r.vpcf"
                            }
                        }
                    }
                    "2"
                    {
                        "model"                 "models/items/ember_spirit/rapier_burning_god_offhand/rapier_burning_god_offhand.vmdl"
                        "particles"
                        {
                            "1"
                            {
                                "particle"      "particles/econ/items/ember_spirit/ember_spirit_burning_god_offhand/ember_spirit_ambient_burning_god_l.vpcf"
                            }
                        }
                    }
                }
            }
        } 
    }
    "npc_dota_hero_windrunner"
    {
        "__particles"
        {
            "__default"
            {
                "particles"
                {
                    "1" 
                    {
                        "particle"          "particles/hela/hela_ambient.vpcf"
                        "ControlPoints"
                        {
                            "1"
                            {
                                "attach_point"      "attach_eye_l"
                            }
                            "2"
                            {
                                "attach_point"      "attach_eye_r"
                            }
                        }
                    } 
                }
            }
        }
        "weapon"
        {
            "__default"
            {
                "models"
                {
                    "1"
                    {
                        "model"     "models/heroes/hero_hela/weapon/hela_weap.vmdl"
                    }                
                }   
            }
            "fate_of_asgard"
            {
                "models"
                {
                    "1"
                    {
                        "model"     "models/heroes/hero_hela/fate_of_asgard/fate_of_asgard_right.vmdl"
                    }            
                }   
            }
            "golden_fate_of_asgard"
            {
                "models"
                {
                    "1"
                    {
                        "model"     "models/heroes/hero_hela/fate_of_asgard/fate_of_asgard_right.vmdl"
                        "material"  "gold"
                        "particles"
                        {
                            "1"
                            {
                                "particle"      "particles/hero_hela/dagger_golden_ambient.vpcf"
                            }
                        }
                    }                 
                }   
            }
        }     
    }
    "npc_dota_hero_queenofpain"
    {   
        "__particles"
        {
            "__default"
            {
                "particles"
                {
                    "1" 
                    {
                        "particle"          "particles/econ/items/treant_protector/ancient_treant/ancient_treant_ambient_eyes.vpcf"
                        "ControlPoints"
                        {
                            "0"
                            {
                                "attach_point"      "attach_eye_l"
                            }
                            "6"
                            {
                                "attach_point"      "attach_eye_l"
                            }
                            "7"
                            {
                                "attach_point"      "attach_eye_l"
                            }
                            "10"
                            {
                                "attach_point"      "attach_eye_l"
                            }
                        }
                    } 
                    "2" 
                    {
                        "particle"          "particles/econ/items/treant_protector/ancient_treant/ancient_treant_ambient_eyes.vpcf"
                        "ControlPoints"
                        {
                            "0"
                            {
                                "attach_point"      "attach_eye_r"
                            }
                            "6"
                            {
                                "attach_point"      "attach_eye_r"
                            }
                            "7"
                            {
                                "attach_point"      "attach_eye_r"
                            }
                            "10"
                            {
                                "attach_point"      "attach_eye_r"
                            }
                        }
                    } 
                }
            }
            "voland"
            {
                "particles"
                {
                    "1" 
                    {
                        "particle"          "particles/econ/courier/courier_jade_horn/courier_jade_horn_ambient_eye.vpcf"
                        "ControlPoints"
                        {
                            "0"
                            {
                                "attach_point"      "attach_eye_l"
                            }
                        }
                    } 
                    "2" 
                    {
                        "particle"          "particles/econ/courier/courier_jade_horn/courier_jade_horn_ambient_eye.vpcf"
                        "ControlPoints"
                        {
                            "0"
                            {
                                "attach_point"      "attach_eye_r"
                            }
                        }
                    } 
                }
            }
        }
        "head"
        {          
            "chaos_rising"
            {
               "models"
                {
                    "1"
                    {                   
                        "model"     "models/heroes/hero_slaanesh/immortal_head/immortal_head_v2.vmdl"
                        "particles"
                        {
                            "1"
                            {
                                "particle"      "particles/slaanesh/immortal_head_ambient.vpcf"
                                "ControlPoints"
                                {
                                    "3"         "attach_pingtail_l"
                                    "4"         "attach_pingtail_r"
                                }
                                
                            }
                            "2"
                            {
                                "particle"      "particles/econ/courier/courier_platinum_roshan/platinum_roshan_eyes.vpcf"
                                "ControlPoints"
                                {
                                    "0"         "attach_l_eyebrow"
                                    "1"         "attach_l_eyebrow"
                                    "2"         "attach_r_eyebrow"
                                }
                            }
                        }
                    }            
                }   
            }
            "voland"
            {

            }
        } 
        "weapon"
        {
            "__default"
            {
                "models"
                {
                    "1"
                    {
                        "model"         "models/heroes/hero_slaanesh/weapons/weapon_final.vmdl"
                    }
                }
            }
            "shards_of_creation"
            {
                "models"
                {
                    "1"
                    {
                        "model"         "models/heroes/hero_slaanesh/weapons/immortal_weapon_1.vmdl"
                    }
                }
            }
            "golden_shards_of_creation"
            {
                "models"
                {
                    "1"
                    {
                        "model"         "models/heroes/hero_slaanesh/weapons/immortal_weapon_1.vmdl"
                        "material"      "gold"
                    }
                }
            }
            "voland"
            {
                "model"                 "models/heroes/hero_slaanesh/voland_skin/voland.vmdl"
                "models"
                {
                    "1"
                    {
                        "model"         "models/heroes/hero_slaanesh/voland_skin/wand/wand.vmdl"
                    }
                }
                "particles"
                {
                    "1" 
                    {
                        "particle"          "particles/voland.vpcf"
                    }
                }
                "modifiers"
                {
                    "1"
                    {
                        "modifier"          "modifier_voland_custom"
                        "modifier_path"     "modifiers/modifier_voland_custom.lua"
                    }
                }    
            }
        }
    }
    "npc_dota_hero_godspeed"
    {   
        "weapon"
        {
           "basher_blades"
           {
               "models"
               {
                   "0"
                   {
                       "model"          "models/items/antimage/skullbasher/skullbasher_offhand.vmdl"
                       "particles"
                       {
                           "0"
                           {
                               "particle"       "particles/econ/items/antimage/antimage_weapon_basher_ti5/antimage_ambient_skullbasher_offhand.vpcf"
                           }
                       }
                   }
                   "1"
                   {
                       "model"          "models/items/antimage/skullbasher/skullbasher.vmdl"
                       "particles"
                       {
                           "0"
                           {
                               "particle"       "particles/econ/items/antimage/antimage_weapon_basher_ti5/antimage_ambient_skullbasher.vpcf"
                           }
                       }
                   }
               }
           }
           "golden_basher_blades"
           {
               "models"
               {
                   "0"
                   {
                       "model"          "models/items/antimage/skullbasher/skullbasher_gold_offhand.vmdl"
                       "particles"
                       {
                           "0"
                           {
                               "particle"       "particles/econ/items/antimage/antimage_weapon_basher_ti5_gold/antimage_ambient_skullbasher_offhand_gold.vpcf"
                           }
                       }
                   }
                   "1"
                   {
                       "model"          "models/items/antimage/skullbasher/skullbasher_gold.vmdl"
                       "particles"
                       {
                           "0"
                           {
                               "particle"       "particles/econ/items/antimage/antimage_weapon_basher_ti5_gold/antimage_ambient_skullbasher_gold.vpcf"
                           }
                       }
                   }
               }
           }
        }       
    }
    "npc_dota_hero_enchantress"
    {
        "global"
        {
            "sombra"
            {
                "model"         "models/heroes/tracer/sombra/sombra.vmdl"
                "models"
                {
                    "1"
                    {
                        "model" "models/heroes/tracer/sombra/econs/weapon.vmdl"
                    }
                    "2"
                    {
                        "model" "models/heroes/tracer/sombra/econs/hair.vmdl"
                    }
                }
                "particles"
                {
                    "1"
                    {
                        "particle"  "particles/hero_tracer/sombra_ambient.vpcf"
                        "ControlPoints"
                        {
                            "1"
                            {
                                "attach_point"      "attach_attack1"
                            }
                        }
                    }
                }
                "projectile"
                {
                    "particle"              "particles/items4_fx/nullifier_proj.vpcf"
                }
                "modifiers"
                {
                    "1"
                    {
                        "modifier"          "modifier_arcana"
                        "modifier_path"     "modifiers/modifier_arcana.lua"
                    }
                }   
            }
        }
    }
    "npc_dota_hero_molag_bal"
    {
        "weapon"
        {
            "__default"
            {               
                "models"
                {
                    "1"
                    {
                        "model"     "models/heroes/hero_molag_bal/econs/mace/mace.vmdl"                       
                    }
                }             
            }
        }
    }
    "npc_dota_hero_ancient_apparition"
    {
        "armor"
        {
            "void_of_darkness"
            {               
                "models"
                {
                    "1"
                    {
                        "model"     "models/heroes/hero_qucksilver/econs/void_of_darkness.vmdl"            
                    }
                }
                "particles"
                {
                    "1"
                    {
                        "particle"  "particles/hero_quicksilver/void_of_darkness.vpcf"                    
                    }
                } 
                "modifiers"
                {
                    "1"
                    {
                        "modifier"          "modifier_arcana"
                        "modifier_path"     "modifiers/modifier_arcana.lua"
                    }
                }              
            }
        }
    }
    "npc_dota_hero_doctor_fate"
    {
        "__particles"
        {
            "__default"
            {
                "particles"
                {
                    "1" 
                    {
                        "particle"          "particles/hero_doctor_fate/fate_ambient_eyes.vpcf"
                        "ControlPoints"
                        {
                            "0"
                            {
                                "attach_point"      "attach_eye_l"
                            }
                            "1"
                            {
                                "attach_point"      "attach_eye_r"
                            }
                        }
                    } 
                    "2" 
                    {
                        "particle"          "particles/hero_doctor_fate/fate_ambient.vpcf"   
                        "ControlPoints"
                        {
                            "1"
                            {
                                "attach_point"      "attach_head"
                            }
                            "4"
                            {
                                "attach_point"      "attach_attack1"
                            }
                        }                
                    } 
                }
            }
        } 
    }
    "npc_dota_hero_pugna"
    {
        "weapon"
        {
            "hellspont_immortal_axe"
            {
                "particles"
                {
                    "1" 
                    {
                        "particle"          "particles/econ/items/riki/riki_head_ti8_crimson/riki_head_ambient_ti8_crimson_head.vpcf"
                        "ControlPoints"
                        {
                            "1"
                            {
                                "attach_point"      "attach_head"
                            }
                        }
                    } 
                    "2" 
                    {
                        "particle"          "particles/hellspont/hellspont_ambient.vpcf"                 
                    } 
                    "3" 
                    {
                        "particle"          "particles/econ/items/undying/undying_manyone/undying_pale_gold_tombstone_ambient_eyes.vpcf"
                        "ControlPoints"
                        {
                            "1"
                            {
                                "attach_point"      "attach_eye_l"
                            }
                            "2"
                            {
                                "attach_point"      "attach_eye_r"
                            }
                        }
                    } 
                }
                "models"
                {
                    "1"
                    {
                        "model"             "models/heroes/hero_hellspont/helmet/hellspont_immortal_axe.vmdl"            
                    }
                }
                "modifiers"
                {
                    "1"
                    {
                        "modifier"          "modifier_hellspont"
                        "modifier_path"     "modifiers/modifier_hellspont.lua"
                    }
                } 
            }
            "__default"
            {
               "particles"
                {
                    "1" 
                    {
                        "particle"          "particles/hero_hellspont/hellspont_ambient.vpcf"
                        "ControlPoints"
                        {
                            "0"
                            {
                                "attach_point"      "attach_head"
                            }
                            "1"
                            {
                                "attach_point"      "attach_eye_l"
                            }
                            "2"
                            {
                                "attach_point"      "attach_eye_r"
                            }
                            "9"
                            {
                                "attach_point"      "attach_head"
                            }
                            "10"
                            {
                                "attach_point"      "attach_head"
                            }
                            "12"
                            {
                                "attach_point"      "attach_head"
                            }
                        }
                    } 
                } 
            }
        } 
    }
    "npc_dota_hero_legion_commander"
    {
        "hair"
        {
            "__default"
            {
                "models"
                {
                    "1"
                    {
                        "model"             "models/heroes/hero_marvel/hair.vmdl"            
                    }                  
                }
            }
        }      
    }
    "npc_dota_hero_magnataur"
    {
        "armor"
        {
            "white_panther"
            {
                "material"      "white"
            }
        }      
    }
    "npc_dota_hero_shredder"
    {
        "weapon_left"
        {
            "khan_blade_of_fate"
            {
                "models"
                {
                    "1"
                    {
                        "model"             "models/heroes/han/khan_blades_of_fate/khan_blade_of_fate.vmdl"            
                    }
                }
            }
            "khan_manifold_paradox"
            {
                "models"
                {
                    "1"
                    {
                        "model"             "models/heroes/han/khan_manifold_paradox/manifold_paradox.vmdl"            
                    }
                }
               "particles"
                {
                    "1" 
                    {
                        "particle"          "particles/units/heroes/hero_spectre/spectre_ambient.vpcf"
                    } 
                }         
                "modifiers"
                {
                    "1"
                    {
                        "modifier"          "modifier_khan"
                        "modifier_path"     "modifiers/modifier_khan.lua"
                    }
                }
            }
            "__default"
            {
              "models"
                {
                    "1"
                    {
                        "model"             "models/heroes/han/han_weapon.vmdl"            
                    }
                }
            }
            "nemesis_custom"
            {

            }
        } 
        "weapon_right"
        {
            "khan_blade_of_fate"
            {
              "models"
               {
                    "1"
                    {
                        "model"             "models/heroes/han/khan_blades_of_fate/khan_blade_of_fate_offhand.vmdl"
                    }
               }
            }
            "khan_manifold_paradox"
            {
              "models"
               {
                    "1"
                    {
                        "model"             "models/heroes/han/khan_manifold_paradox/manifold_paradox_offhand.vmdl"
                    }
               }
            }
            "__default"
            {
               "models"
               {
                    "1"
                    {
                        "model"             "models/heroes/han/han_weapon_offhand.vmdl"
                    }
               }
            }
            "nemesis_custom"
            {

            }
        } 
        "armor"
        {
            "__default"
            {
                "models"
                {
                    "1"
                    {
                        "model"             "models/items/antimage/avenging_anchorite_armor/avenging_anchorite_armor.vmdl"
                    }
                }
            }
            "nemesis_custom"
            {

            }
        }
        "belt"
        {
            "__default"
            {
                "models"
                {
                    "1"
                    {
                        "model"             "models/items/antimage/distinguished_conscript_belt/distinguished_conscript_belt.vmdl"
                    }
                }
            }
            "nemesis_custom"
            {
                "model"                     "models/heroes/han/nemesis_custom/nemesis.vmdl"
                "modifiers"
                {
                    "1"
                    {
                        "modifier"          "modifier_nemesis"
                        "modifier_path"     "modifiers/modifier_nemesis.lua"
                    }
                }    
            }
        }
        "head"
        {
            "__default"
            {
                "models"
                {
                    "1"
                    {
                        "model"             "models/heroes/han/khan_blades_of_fate/khan_winters_wind.vmdl"
                    }
                }
            }
            "nemesis_custom"
            {

            }
        }
    }
    "npc_dota_hero_bloodseeker"
    {
        "armor"
        {
            "flash_custom"
            {
                "model"                     "models/heroes/hero_flash/flash_custom/flash.vmdl"   
                "modifiers"
                {
                    "1"
                    {
                        "modifier"          "modifier_flash_custom"
                        "modifier_path"     "modifiers/modifier_flash_custom.lua"
                    }
                }              
            }
        }      
    }
    "npc_dota_hero_dazzle"
    {
        "global"
        {
            "joker_custom"
            {
                "model"                     "models/heroes/hero_joker/joker_custom/joker.vmdl"    
                "particles"
                {
                    "1" 
                    {
                        "particle"          "particles/hero_joker/joker_ambient.vpcf"
                    } 
                }         
                "modifiers"
                {
                    "1"
                    {
                        "modifier"          "modifier_joker_custom"
                        "modifier_path"     "modifiers/modifier_joker_custom.lua"
                    }
                }          
            }
        }      
    }
    "npc_dota_hero_rattletrap"
    {
        "armor"
        {       
            "dark_custom"
            {
                "model"         "models/heroes/dark_custom/jeanne.vmdl"
                "models"
                {
                    "1"
                    {
                        "model"     "models/heroes/dark_custom/flag.vmdl"
                    }
                    "2"
                    {
                        "model"     "models/heroes/dark_custom/dress.vmdl"
                    }
                    "3"
                    {
                        "model"     "models/heroes/dark_custom/sword.vmdl"
                        "particles"
                        {
                            "1"
                            {
                                "particle"          "particles/effects/jeannie_sword.vpcf"
                            }
                        }
                    }
                    "4"
                    {
                        "model"     "models/heroes/dark_custom/hair.vmdl"
                    }
                }   
                "modifiers"
                {
                    "1"
                    {
                        "modifier"          "modifier_jeannie_arcana"
                        "modifier_path"     "modifiers/modifier_jeannie_arcana.lua"
                    }
                }
                "particles"
                {
                    "1"
                    {
                        "particle"      "particles/econ/courier/courier_jadehoof_ambient/jadehoof_ambient.vpcf"
                    }
                }
            }
        }
    }
    "npc_dota_hero_mercer"
    {
        "__default"
        {       
            "__default"
            {
                "modifiers"
                {
                    "1"
                    {
                        "modifier"          "modifier_mercer"
                        "modifier_path"     "modifiers/modifier_mercer.lua"
                    }
                }
            }
        }
        "arms"
        {
            "__default"
            {
                "models"
                {
                    "1" 
                    {
                        "model"         "models/heroes/hero_mercer/econs/arms.vmdl"
                    }
                }
            }
        }
    }
}