"qualities"
{
  "1"
  {
    "name" "default"
  }
  "2"
  {
    "name" "genuine"
  }
  "3"
  {
    "name" "elder"
  }
  "4"
  {
    "name" "unusual"
  }
  "5"
  {
    "name" "unique"
  }
  "6"
  {
    "name" "strange"
  }
  "7"
  {
    "name" "haunted"
  }
  "8"
  {
    "name" "tournament"
  }
  "9"
  {
    "name" "ascendant"
  }
  "10"
  {
    "name" "favored"
  }
  "10"
  {
    "name" "legacy"
  }
}
